version: "3.8"

services:
  brontes-api:
    build:
      context: .
      dockerfile: ./docker/brontesAPI/Dockerfile.api.prod
    volumes:
      - ./brontes:/app/brontes
    ports:
      - 8080:8080
    env_file:
      - .env.staging
    networks:
      - local

networks:
  local:
