version: "3.7"

services:
  timescale:
    image: timescale/timescaledb:latest-pg14
    volumes: 
      - timescale-volume:/home/postgres/pgdata/data
    environment:
      POSTGRES_PASSWORD: pgadmin
    ports:
      - 5432:5432

  node:
    image: node-app:latest
    ports:
      - 3000:3000
    volumes:
      - ./node:/usr/src/app
    environment:
      NEO4J_URL: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASS: test
      PORT: 3000

  neo4j:
    image: neo4j:4.4
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/test
      NEO4J_apoc_export_file_enabled: true 
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true
      NEO4JLABS_PLUGINS: '["apoc", "n10s"]'
    ports:
      - 7474:7474
      - 7687:7687

  bim_to_brick:
    image: bim_to_brick:latest
    ports:
      - 8000:8000
    volumes: 
      - ./bim_to_brick:/usr/src/app
    platform: linux/amd64


volumes:
  timescale-volume:
