version: "3.8"

services:
  brontes-server:
    container_name: server
    image: server:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    volumes:
      - ./brontes:/app/brontes
    ports:
      - 8080:8080
    env_file:
      - .env.beta
    networks:
      - local

networks:
  local:
