version: "3.8"

services:
  brontes-api:
    container_name: brontes-api
    image: brontes-api:beta
    build:
      context: .
      dockerfile: ./docker/brontesAPI/Dockerfile.api.prod
    volumes:
      - ./brontes:/app/brontes
    ports:
      - 8080:8080
    env_file:
      - .env.beta
    networks:
      - local

networks:
  local:
