version: "3.7"

services:
  timescale:
    image: timescale/timescaledb:latest-pg14
    volumes: 
      - timescale-volume:/home/postgres/pgdata/data
    environment:
      POSTGRES_PASSWORD: pgadmin
    ports:
      - 5432:5432

  node:
    image: node-app:latest
    ports:
      - 3000:3000
    volumes:
      - ./node:/usr/src/app
    environment:
      NEO4J_URL: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASS: test
      PORT: 3000

  neo4j:
    image: neo4j:latest
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/test
    ports:
      - 7474:7474
      - 7687:7687

  py_server:
    image: py_server:latest
    ports:
      - 8000:8000
    volumes: 
      - ./py_server:/usr/src/app
    platform: linux/amd64


volumes:
  timescale-volume:
