version: "3.8"
services:
  brontes-api:
    build:
      context: .
      dockerfile: ./docker/brontesAPI/Dockerfile.api.local
    volumes:
      - ./brontes:/app/brontes
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - NEO4J_URI=bolt://neo4j_with_plugins:7687
      - POSTGRES_CONNECTION_STRING=postgresql://postgres:postgres@pg:5432/postgres
      - UNSTRUCTURED_URL=http://unstructured:8000
    networks:
      - local
    depends_on:
      - neo4j_with_plugins
      - pg

  unstructured:
    image: quay.io/unstructured-io/unstructured-api:latest
    ports:
      - 8000:8000
    networks:
      - local

  pg:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile.pg
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - local

  neo4j_with_plugins:
    build:
      context: .
      dockerfile: ./docker/neo4j/Dockerfile.neo4j
    volumes:
      - neo4jdata:/data
      - neo4jlogs:/logs
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - local

networks:
  local:

volumes:
  postgresqldata:
  neo4jdata:
  neo4jlogs:
