version: "3.8"
services:
  open-operator-server:
    container_name: server
    image: server
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    volumes:
      - ./openoperator:/app/openoperator
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - NEO4J_URI=bolt://neo4j_with_plugins:7687
      - POSTGRES_CONNECTION_STRING=postgresql://postgres:postgres@pg:5432/postgres
      - UNSTRUCTURED_URL=http://unstructured:8000
    networks:
      - local
    depends_on:
      - neo4j_with_plugins
      - pg

  unstructured:
    container_name: unstructured
    image: quay.io/unstructured-io/unstructured-api:latest
    ports:
      - 8000:8000
    networks:
      - local

  pg:
    container_name: pg
    image: pg
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile.pg
    volumes:
      - ./.postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - local

  neo4j_with_plugins:
    container_name: neo4j_with_plugins
    image: neo4j_with_plugins
    build:
      context: .
      dockerfile: ./docker/neo4j/Dockerfile.neo4j
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/plugins
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - local

networks:
  local:
